In [1]:
import pandas as pd

In [2]:
df3 = pd.read_csv('../../../Data/raw_data/3. Top Hits Spotify from 2000-2019.csv')
df3

,artist,song,duration_ms,explicit,year,popularity,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,genre
0,Britney Spears,Oops!...I Did It Again,211160,False,2000,77,0.751,0.834,1,-5.444,0,0.0437,0.3000,0.000018,0.3550,0.894,95.053,pop
1,blink-182,All The Small Things,167066,False,1999,79,0.434,0.897,0,-4.918,1,0.0488,0.0103,0.000000,0.6120,0.684,148.726,"rock, pop"
2,Faith Hill,Breathe,250546,False,1999,66,0.529,0.496,7,-9.007,1,0.0290,0.1730,0.000000,0.2510,0.278,136.859,"pop, country"
3,Bon Jovi,It's My Life,224493,False,2000,78,0.551,0.913,0,-4.063,0,0.0466,0.0263,0.000013,0.3470,0.544,119.992,"rock, metal"
4,*NSYNC,Bye Bye Bye,200560,False,2000,65,0.614,0.928,8,-4.806,0,0.0516,0.0408,0.001040,0.0845,0.879,172.656,pop
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,Jonas Brothers,Sucker,181026,False,2019,79,0.842,0.734,1,-5.065,0,0.0588,0.0427,0.000000,0.1060,0.952,137.958,pop
1996,Taylor Swift,Cruel Summer,178426,False,2019,78,0.552,0.702,9,-5.707,1,0.1570,0.1170,0.000021,0.1050,0.564,169.994,pop
1997,Blanco Brown,The Git Up,200593,False,2019,69,0.847,0.678,9,-8.635,1,0.1090,0.0669,0.000000,0.2740,0.811,97.984,"hip hop, country"
1998,Sam Smith,Dancing With A Stranger (with Normani),171029,False,2019,75,0.741,0.520,8,-7.513,1,0.0656,0.4500,0.000002,0.2220,0.347,102.998,pop
1999,Post Malone,Circles,215280,False,2019,85,0.695,0.762,0,-3.497,1,0.0395,0.1920,0.002440,0.0863,0.553,120.042,hip hop

In [3]:
#what is possible to gather from this data set ?
    # top songs (most played songs) on spotify for decade 2010-2019
    # get the most popular genres for this specific date seeing spotify plays
    # need to normalize the genres names and also the artist names to concatenate with other data sets?
    # get agreggations by year ?

In [4]:
df3.columns

Index(['artist', 'song', 'duration_ms', 'explicit', 'year', 'popularity',
       'danceability', 'energy', 'key', 'loudness', 'mode', 'speechiness',
       'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo',
       'genre'],
      dtype='object')

In [5]:
#Columns don't needed since most of all are techincal sound parameteres used by alghoritim's Spotify 
    # to predict the popularity of a song.

df3 = df3.drop(['duration_ms', 'explicit','danceability', 'energy', 'key', 'loudness', 'mode', 'speechiness',
       'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo','song'], axis = 1)

In [6]:
df3

              artist  year  popularity             genre
0     Britney Spears  2000          77               pop
1          blink-182  1999          79         rock, pop
2         Faith Hill  1999          66      pop, country
3           Bon Jovi  2000          78       rock, metal
4             *NSYNC  2000          65               pop
...              ...   ...         ...               ...
1995  Jonas Brothers  2019          79               pop
1996    Taylor Swift  2019          78               pop
1997    Blanco Brown  2019          69  hip hop, country
1998       Sam Smith  2019          75               pop
1999     Post Malone  2019          85           hip hop

[2000 rows x 4 columns]

In [7]:
df3.info() # --> No null values in the current columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   artist      2000 non-null   object
 1   year        2000 non-null   int64
 2   popularity  2000 non-null   int64
 3   genre       2000 non-null   object
dtypes: int64(2), object(2)
memory usage: 62.6+ KB

In [8]:
df3 = df3.rename(columns = {'artist':'artist_name', 'year':'year'}) # to become normalize with df1 and df2

In [9]:
df3

         artist_name  year  popularity             genre
0     Britney Spears  2000          77               pop
1          blink-182  1999          79         rock, pop
2         Faith Hill  1999          66      pop, country
3           Bon Jovi  2000          78       rock, metal
4             *NSYNC  2000          65               pop
...              ...   ...         ...               ...
1995  Jonas Brothers  2019          79               pop
1996    Taylor Swift  2019          78               pop
1997    Blanco Brown  2019          69  hip hop, country
1998       Sam Smith  2019          75               pop
1999     Post Malone  2019          85           hip hop

[2000 rows x 4 columns]

In [10]:
import time
from datetime import date

def transform_to_date(x):
    x = pd.to_datetime(x, errors='coerce', format='%Y')
    return x.year

df3['year'] = df3['year'].apply(transform_to_date) # to become normalize with df1 and df2

In [11]:
df3['genre'].value_counts() # To check the values and to see if the funcion setted in df1
    #for cleaning columns'genres' works here.

pop                                      428
hip hop, pop                             277
hip hop, pop, R&B                        244
pop, Dance/Electronic                    221
pop, R&B                                 178
hip hop                                  124
hip hop, pop, Dance/Electronic            78
rock                                      58
rock, pop                                 43
Dance/Electronic                          41
rock, metal                               38
pop, latin                                28
pop, rock                                 26
set()                                     22
hip hop, Dance/Electronic                 16
latin                                     15
pop, rock, metal                          14
hip hop, pop, latin                       14
R&B                                       13
pop, rock, Dance/Electronic               13
country                                   10
metal                                      9
hip hop, pop, rock                         9
rock, pop, Dance/Electronic                8
pop, Folk/Acoustic                         8
pop, country                               8
pop, R&B, Dance/Electronic                 6
rock, pop, metal                           4
hip hop, pop, R&B, Dance/Electronic        3
hip hop, R&B                               3
hip hop, pop, R&B, latin                   3
World/Traditional, pop, Folk/Acoustic      2
pop, rock, Folk/Acoustic                   2
pop, easy listening, jazz                  2
World/Traditional, rock                    2
rock, blues, latin                         2
World/Traditional, rock, pop               2
hip hop, rock, pop                         2
rock, blues                                2
Folk/Acoustic, pop                         2
World/Traditional, hip hop                 2
rock, pop, metal, Dance/Electronic         1
rock, classical                            1
country, latin                             1
hip hop, latin, Dance/Electronic           1
rock, Folk/Acoustic, pop                   1
easy listening                             1
Folk/Acoustic, rock, pop                   1
rock, easy listening                       1
pop, R&B, easy listening                   1
World/Traditional, pop                     1
hip hop, pop, country                      1
rock, Dance/Electronic                     1
rock, R&B, Folk/Acoustic, pop              1
World/Traditional, Folk/Acoustic           1
pop, easy listening, Dance/Electronic      1
Folk/Acoustic, rock                        1
rock, Folk/Acoustic, easy listening        1
hip hop, country                           1
Name: genre, dtype: int64

In [1]:
def normalize_genres(x):
    if ('Rock' in x):
        x=x.replace(x,'Rock')
        return x
    if ('Krautrock' in x):
        x=x.replace(x,'Rock')
        return x
    if ('Punk' in x):
        x=x.replace(x,'Rock')
        return x
    if ('Post-Hardcore' in x):
        x=x.replace(x,'Rock')
        return x
    if ('Midwest Emo' in x):
        x=x.replace(x,'Rock')
        return x
    if ('Slowcore' in x):
        x=x.replace(x,'Rock')
        return x
    if ('Britpop' in x):
        x=x.replace(x,'Rock')
        return x
    if ('Neo-Psychedelia' in x):
        x=x.replace(x,'Rock')
        return x
    if ('Shoegaze' in x):
        x=x.replace(x,'Rock')
        return x
    if ('Grunge' in x):
        x=x.replace(x,'Rock')
        return x
    if ('Neo-Prog' in x):
        x=x.replace(x,'Rock')
        return x
    if ("Baggy/Madchester" in x):
        x=x.replace(x,'Rock')
        return x
    if ('Heavy Psych' in x):
        x=x.replace(x,'Rock')
        return x
    if ('Emo' in x):
        x=x.replace(x,'Rock')
        return x
    if ('Emoviolence' in x):
        x=x.replace(x,'Rock')
        return x
    if ('Latin Alternative' in x):
        x=x.replace(x,'Rock')
        return x
    if ('Symphonic Prog' in x):
        x=x.replace(x,'Rock')
        return x
    if ('Riot Grrrl' in x):
        x=x.replace(x,'Rock')
        return x
    if ('AOR' in x):
        x=x.replace(x,'Rock')
        return x
    if ('Metal' in x):
        x=x.replace(x,'Metal')
        return x
    if ('Grindcore' in x):
        x=x.replace(x,'Metal')
        return x
    if ('Mathcore' in x):
        x=x.replace(x,'Metal')
        return x
    if ('Djent' in x):
        x=x.replace(x,'Metal')
        return x
    if ('Deathgrind' in x):
        x=x.replace(x,'Metal')
        return x
    if ("Death'n'Roll" in x):
        x=x.replace(x,'Metal')
        return x
    if ("Neue Deutsche HÃ¤rte" in x):
        x=x.replace(x,'Metal')
        return x
    if ("Screamo" in x):
        x=x.replace(x,'Metal')
        return x
    if ("Crossover Thrash" in x):
        x=x.replace(x,'Metal')
        return x
    if ("Deathcore" in x):
        x=x.replace(x,'Metal')
        return x
    if ('Pop' in x):
        x=x.replace(x,'Pop')
        return x
    if ('Blues' in x):
        x=x.replace(x,'Blues')
        return x
    if ('Folk' in x):
        x=x.replace(x,'Folk')
        return x
    if ('American Primitivism' in x):
        x=x.replace(x,'Folk')
        return x
    if ('Neofolk' in x):
        x=x.replace(x,'Folk')
        return x
    if ('NuevacanciÃ³nlatinoamericana' in x):
        x=x.replace(x,'Folk')
        return x
    if ('Soul' in x):
        x=x.replace(x,'Soul')
        return x
    if ('R&B' in x):
        x=x.replace(x,'Soul')
        return x
    if ('Jazz' in x):
        x=x.replace(x,'Jazz')
        return x
    if ('Post-Bop' in x):
        x=x.replace(x,'Jazz')
        return x
    if ('Hard-Bop' in x):
        x=x.replace(x,'Jazz')
        return x
    if ('Hard Bop' in x):
        x=x.replace(x,'Jazz')
        return x
    if ('Bossanova' in x):
        x=x.replace(x,'Jazz')
        return x
    if ('Hip-Hop' in x):
        x=x.replace(x,'Hip-Hop')
        return x
    if ('Hip Hop' in x):
        x=x.replace(x,'Hip-Hop')
        return x
    if ('Gangsta Rap' in x):
        x=x.replace(x,'Hip-Hop')
        return x
    if ('Rap' in x):
        x=x.replace(x,'Hip-Hop')
        return x
    if ('Vaportrap' in x):
        x=x.replace(x,'Hip-Hop')
        return x
    if ('Trap' in x):
        x=x.replace(x,'Hip-Hop')
        return x
    if ('Funk' in x):
        x=x.replace(x,'Funk')
        return x
    if ('Americana, Country' in x):
        x=x.replace(x,'Country')
        return x
    if ("Alt-Country" in x):
        x=x.replace(x,'Country')
        return x
    if ("Outlaw Country" in x):
        x=x.replace(x,'Country')
        return x
    if ('Reggae' in x):
        x=x.replace(x,'Reggae')
        return x
    if ('Synthpop' in x):
        x=x.replace(x,'Electronic')
        return x
    if ('Electropop' in x):
        x=x.replace(x,'Electronic')
        return x
    if ('IDM' in x):
        x=x.replace(x,'Electronic')
        return x
    if ('Progressive Electronic' in x):
        x=x.replace(x,'Electronic')
        return x
    if ('Electronic' in x):
        x=x.replace(x,'Electronic')
        return x
    if ('Ambient' in x):
        x=x.replace(x,'Electronic')
        return x
    if ('Industrial' in x):
        x=x.replace(x,'Electronic')
        return x
    if ('Big Beat' in x):
        x=x.replace(x,'Electronic')
        return x
    if ('Downtempo' in x):
        x=x.replace(x,'Electronic')
        return x
    if ('Digital Hardcore' in x):
        x=x.replace(x,'Electronic')
        return x
    if ('Electro-Industrial' in x):
        x=x.replace(x,'Electronic')
        return x
    if ('Techno' in x):
        x=x.replace(x,'Electronic')
        return x
    if ('Electro-Industrial' in x):
        x=x.replace(x,'Electronic')
        return x
    if ('Glitch' in x):
        x=x.replace(x,'Electronic')
        return x
    if ('Deep House' in x):
        x=x.replace(x,'Electronic')
        return x
    if ("Microhouse" in x):
        x=x.replace(x,'Electronic')
        return x
    if ("Atmospheric Drumand Bass" in x):
        x=x.replace(x,'Electronic')
        return x
    if ("Chillwave" in x):
        x=x.replace(x,'Electronic')
        return x
    if ("Berlin School" in x):
        x=x.replace(x,'Electronic')
        return x
    if ("Vaporwave" in x):
        x=x.replace(x,'Electronic')
        return x
    if ("Deconstructed Club" in x):
        x=x.replace(x,'Electronic')
        return x
    if ("Future Garage" in x):
        x=x.replace(x,'Electronic')
        return x
    if ("Indietronica" in x):
        x=x.replace(x,'Electronic')
        return x
    if ("Dungeon Synth" in x):
        x=x.replace(x,'Electronic')
        return x
    if ("French House" in x):
        x=x.replace(x,'Electronic')
        return x
    if ("UKBass" in x):
        x=x.replace(x,'Electronic')
        return x
    if ("Wonky" in x):
        x=x.replace(x,'Electronic')
        return x
    if ("Minimal Synth" in x):
        x=x.replace(x,'Electronic')
        return x
    if ("Progressive House" in x):
        x=x.replace(x,'Electronic')
        return x
    if ("Electro-Disco" in x):
        x=x.replace(x,'Electronic')
        return x
    if ("Outsider House" in x):
        x=x.replace(x,'Electronic')
        return x
    if ("Drilland Bass" in x):
        x=x.replace(x,'Electronic')
        return x
    if ("Acid House" in x):
        x=x.replace(x,'Electronic')
        return x
    else:
        return x

In [13]:

df3['genre']=df3['genre'].str.title() # to the funcion normalize_genres can work, is needed that
    #the values become capitalized in all the words.

df3['genre'] = df3['genre'].apply(normalize_genres)

df3['genre'].value_counts()

Pop               1506
Rock               234
Hip-Hop            144
Electronic          41
Set()               22
Soul                16
Latin               15
Country             10
Metal                9
Folk                 1
Country, Latin       1
Easy Listening       1
Name: genre, dtype: int64

In [14]:
display(df3[df3['genre'] == 'Set()']) # to check wich rows have the label"Set()".

df3[df3['genre'] == 'Set()'] = 'Pop' # it seems that most of them are refered to a pop artist.

          artist_name  year  popularity  genre
95            Wheatus  1999          71  Set()
216       Las Ketchup  2002          66  Set()
291     Blazin' Squad  2012          40  Set()
428    George Michael  2004          57  Set()
455         DJ Casper  2004          51  Set()
481             Eamon  2004          64  Set()
545    Brian McFadden  2004          42  Set()
645              Meck  2005          46  Set()
710          Ida Corr  2012          43  Set()
729     Camille Jones  2006          17  Set()
793     Elliott Yamin  2007          58  Set()
794       Wyclef Jean  2007          56  Set()
949       A.R. Rahman  2009          65  Set()
1057           K'NAAN  2009          57  Set()
1271            Gotye  2011          57  Set()
1320      John Newman  2013          74  Set()
1406           MAGIC!  2014          80  Set()
1454     Milky Chance  2014          73  Set()
1487  Natalie La Rose  2014          66  Set()
1773   Zay Hilfigerrr  2016          57  Set()
1841               EO  2018          67  Set()
1976         Ashley O  2019          57  Set()

In [15]:
df3['genre'].value_counts()

Pop               1528
Rock               234
Hip-Hop            144
Electronic          41
Soul                16
Latin               15
Country             10
Metal                9
Folk                 1
Country, Latin       1
Easy Listening       1
Name: genre, dtype: int64

In [16]:
df3['artist_name'] = df3['artist_name'].str.lower()
df3['genre'] = df3['genre'].str.lower()
df3

         artist_name  year popularity    genre
0     britney spears  2000         77      pop
1          blink-182  1999         79     rock
2         faith hill  1999         66      pop
3           bon jovi  2000         78     rock
4             *nsync  2000         65      pop
...              ...   ...        ...      ...
1995  jonas brothers  2019         79      pop
1996    taylor swift  2019         78      pop
1997    blanco brown  2019         69  hip-hop
1998       sam smith  2019         75      pop
1999     post malone  2019         85  hip-hop

[2000 rows x 4 columns]

In [17]:
df3.to_csv('../../../Data/cleaned_data/3. Top Hits Spotify from 2000-2019[CLEANED].csv', index = False)

In [18]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   artist_name  2000 non-null   object
 1   year         2000 non-null   object
 2   popularity   2000 non-null   object
 3   genre        2000 non-null   object
dtypes: object(4)
memory usage: 62.6+ KB