In [8]:
import pandas as pd

In [9]:
df5 = pd.read_csv('../../../Data/raw_data/5. Spotify-2000.csv')
df5

,Index,Title,Artist,Top Genre,Year,Beats Per Minute (BPM),Energy,Danceability,Loudness (dB),Liveness,Valence,Length (Duration),Acousticness,Speechiness,Popularity
0,1,Sunrise,Norah Jones,adult standards,2004,157,30,53,-14,11,68,201,94,3,71
1,2,Black Night,Deep Purple,album rock,2000,135,79,50,-11,17,81,207,17,7,39
2,3,Clint Eastwood,Gorillaz,alternative hip hop,2001,168,69,66,-9,7,52,341,2,17,69
3,4,The Pretender,Foo Fighters,alternative metal,2007,173,96,43,-4,3,37,269,0,4,76
4,5,Waitin' On A Sunny Day,Bruce Springsteen,classic rock,2002,106,82,58,-5,10,87,256,1,3,59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1989,1990,Heartbreak Hotel,Elvis Presley,adult standards,1958,94,21,70,-12,11,72,128,84,7,63
1990,1991,Hound Dog,Elvis Presley,adult standards,1958,175,76,36,-8,76,95,136,73,6,69
1991,1992,Johnny B. Goode,Chuck Berry,blues rock,1959,168,80,53,-9,31,97,162,74,7,74
1992,1993,Take Five,The Dave Brubeck Quartet,bebop,1959,174,26,45,-13,7,60,324,54,4,65
1993,1994,Blueberry Hill,Fats Domino,adult standards,1959,133,50,49,-10,16,83,148,74,3,56

In [10]:
#what is possible to gather from this data set ?
    # top songs (most played songs) on spotify for decade until 2000 (interval that i'm interested in here)
    # get the most popular genres in all decades to compare with data sets that are not using spotify datas
    # need to normalize the genres names and also the artist names to concatenate with other data sets?
    # get agreggations by year ?

In [11]:
df5.columns

df5 = df5.drop(['Index','Beats Per Minute (BPM)', 'Energy', 'Danceability', 'Loudness (dB)',
       'Liveness', 'Valence', 'Length (Duration)', 'Acousticness',
       'Speechiness', 'Title'], axis = 1)

In [12]:
df5 = df5.rename(columns = {'Artist':'artist_name','Top Genre': 'genre', 'Popularity':'popularity', 'Year':'year'})

In [13]:
df5.info() # No Nan values

#column 'year'
import time
from datetime import date

def transform_to_date(x):
    x = pd.to_datetime(x, errors='coerce', format='%Y')
    return x.year

df5['year'] = df5['year'].apply(transform_to_date)

#column 'artist_name'

df5['artist_name'] = df5['artist_name'].str.lower()

df5['artist_name'].value_counts().head(40)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1994 entries, 0 to 1993
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   artist_name  1994 non-null   object
 1   genre        1994 non-null   object
 2   year         1994 non-null   int64
 3   popularity   1994 non-null   int64
dtypes: int64(2), object(2)
memory usage: 62.4+ KB

queen                           37
the beatles                     36
coldplay                        27
u2                              26
the rolling stones              24
bruce springsteen               23
michael jackson                 23
abba                            22
david bowie                     21
fleetwood mac                   18
blÃ¸f                            17
elvis presley                   17
george michael                  16
marco borsato                   15
muse                            15
adele                           14
dire straits                    14
anouk                           13
creedence clearwater revival    13
de dijk                         13
pink floyd                      13
bee gees                        12
eagles                          12
golden earring                  12
prince                          12
ed sheeran                      12
nirvana                         11
supertramp                      11
red hot chili peppers           11
metallica                       11
andre hazes                     11
elton john                      11
boudewijn de groot              10
billy joel                      10
kensington                      10
foo fighters                     9
r.e.m.                           9
guns n' roses                    9
imagine dragons                  9
genesis                          9
Name: artist_name, dtype: int64

In [14]:
#column 'genre'

def normalize_genres(x):
    if ('Rock' in x):
        x=x.replace(x,'Rock')
        return x
    if ('rock' in x):
        x=x.replace(x,'Rock')
        return x
    if ('Krautrock' in x):
        x=x.replace(x,'Rock')
        return x
    if ('Punk' in x):
        x=x.replace(x,'Rock')
        return x
    if ('Post-Hardcore' in x):
        x=x.replace(x,'Rock')
        return x
    if ('Midwest Emo' in x):
        x=x.replace(x,'Rock')
        return x
    if ('Slowcore' in x):
        x=x.replace(x,'Rock')
        return x
    if ('Britpop' in x):
        x=x.replace(x,'Rock')
        return x
    if ('Neo-Psychedelia' in x):
        x=x.replace(x,'Rock')
        return x
    if ('Shoegaze' in x):
        x=x.replace(x,'Rock')
        return x
    if ('Grunge' in x):
        x=x.replace(x,'Rock')
        return x
    if ('Neo-Prog' in x):
        x=x.replace(x,'Rock')
        return x
    if ("Baggy/Madchester" in x):
        x=x.replace(x,'Rock')
        return x
    if ('Heavy Psych' in x):
        x=x.replace(x,'Rock')
        return x
    if ('Emo' in x):
        x=x.replace(x,'Rock')
        return x
    if ('Emoviolence' in x):
        x=x.replace(x,'Rock')
        return x
    if ('Latin Alternative' in x):
        x=x.replace(x,'Rock')
        return x
    if ('Symphonic Prog' in x):
        x=x.replace(x,'Rock')
        return x
    if ('Riot Grrrl' in x):
        x=x.replace(x,'Rock')
        return x
    if ('AOR' in x):
        x=x.replace(x,'Rock')
        return x
    if ('Dutch Indie' in x):
        x=x.replace(x,'Rock')
        return x
    if ('Permanent Wave' in x):
        x=x.replace(x,'Rock')
        return x
    if ('Mellow Gold' in x):
        x=x.replace(x,'Rock')
        return x
    if ('Dutch Prog' in x):
        x=x.replace(x,'Rock')
        return x
    if ('Australian Psych' in x):
        x=x.replace(x,'Rock')
        return x
    if ('Cyberpunk' in x):
        x=x.replace(x,'Rock')
        return x
    if ('Ccm' in x):
        x=x.replace(x,'Rock')
        return x
    if ('Icelandic Indie' in x):
        x=x.replace(x,'Rock')
        return x
    if ('Metal' in x):
        x=x.replace(x,'Metal')
        return x
    if ('Grindcore' in x):
        x=x.replace(x,'Metal')
        return x
    if ('Mathcore' in x):
        x=x.replace(x,'Metal')
        return x
    if ('Djent' in x):
        x=x.replace(x,'Metal')
        return x
    if ('Deathgrind' in x):
        x=x.replace(x,'Metal')
        return x
    if ("Death'n'Roll" in x):
        x=x.replace(x,'Metal')
        return x
    if ("Neue Deutsche HÃ¤rte" in x):
        x=x.replace(x,'Metal')
        return x
    if ("Screamo" in x):
        x=x.replace(x,'Metal')
        return x
    if ("Crossover Thrash" in x):
        x=x.replace(x,'Metal')
        return x
    if ("metal" in x):
        x=x.replace(x,'Metal')
        return x
    if ("Deathcore" in x):
        x=x.replace(x,'Metal')
        return x
    if ('Pop' in x):
        x=x.replace(x,'Pop')
        return x
    if ('pop' in x):
        x=x.replace(x,'Pop')
        return x
    if ('Boy Band' in x):
        x=x.replace(x,'Pop')
        return x
    if ('Classic Schlager' in x):
        x=x.replace(x,'Pop')
        return x
    if ('Levenslied' in x):
        x=x.replace(x,'Pop')
        return x
    if ('Blues' in x):
        x=x.replace(x,'Blues')
        return x
    if ('Folk' in x):
        x=x.replace(x,'Folk')
        return x
    if ('American Primitivism' in x):
        x=x.replace(x,'Folk')
        return x
    if ('Neofolk' in x):
        x=x.replace(x,'Folk')
        return x
    if ('NuevacanciÃ³nlatinoamericana' in x):
        x=x.replace(x,'Folk')
        return x
    if ('Soul' in x):
        x=x.replace(x,'Soul')
        return x
    if ('R&B' in x):
        x=x.replace(x,'Soul')
        return x
    if ('Motown' in x):
        x=x.replace(x,'Soul')
        return x
    if ('Diva House' in x):
        x=x.replace(x,'Soul')
        return x
    if ('Jazz' in x):
        x=x.replace(x,'Jazz')
        return x
    if ('Post-Bop' in x):
        x=x.replace(x,'Jazz')
        return x
    if ('Hard-Bop' in x):
        x=x.replace(x,'Jazz')
        return x
    if ('Hard Bop' in x):
        x=x.replace(x,'Jazz')
        return x
    if ('Bossanova' in x):
        x=x.replace(x,'Jazz')
        return x
    if ('jazz' in x):
        x=x.replace(x,'Jazz')
        return x
    if ('Hip-Hop' in x):
        x=x.replace(x,'Hip-Hop')
        return x
    if ('Hip Hop' in x):
        x=x.replace(x,'Hip-Hop')
        return x
    if ('Hip hop' in x):
        x=x.replace(x,'Hip-Hop')
        return x
    if ('Hip-hop' in x):
        x=x.replace(x,'Hip-Hop')
        return x
    if ('Gangsta Rap' in x):
        x=x.replace(x,'Hip-Hop')
        return x
    if ('Rap' in x):
        x=x.replace(x,'Hip-Hop')
        return x
    if ('Vaportrap' in x):
        x=x.replace(x,'Hip-Hop')
        return x
    if ('Trap' in x):
        x=x.replace(x,'Hip-Hop')
        return x
    if ('Funk' in x):
        x=x.replace(x,'Funk')
        return x
    if ('Disco' in x):
        x=x.replace(x,'Funk')
        return x
    if ('Americana, Country' in x):
        x=x.replace(x,'Country')
        return x
    if ("Alt-Country" in x):
        x=x.replace(x,'Country')
        return x
    if ("Outlaw Country" in x):
        x=x.replace(x,'Country')
        return x
    if ("Country" in x):
        x=x.replace(x,'Country')
        return x
    if ('Reggae' in x):
        x=x.replace(x,'Reggae')
        return x
    if ('Synthpop' in x):
        x=x.replace(x,'Electronic')
        return x
    if ('Electropop' in x):
        x=x.replace(x,'Electronic')
        return x
    if ('IDM' in x):
        x=x.replace(x,'Electronic')
        return x
    if ('Progressive Electronic' in x):
        x=x.replace(x,'Electronic')
        return x
    if ('Electronic' in x):
        x=x.replace(x,'Electronic')
        return x
    if ('Ambient' in x):
        x=x.replace(x,'Electronic')
        return x
    if ('Industrial' in x):
        x=x.replace(x,'Electronic')
        return x
    if ('Big Beat' in x):
        x=x.replace(x,'Electronic')
        return x
    if ('Downtempo' in x):
        x=x.replace(x,'Electronic')
        return x
    if ('Digital Hardcore' in x):
        x=x.replace(x,'Electronic')
        return x
    if ('Electro-Industrial' in x):
        x=x.replace(x,'Electronic')
        return x
    if ('Techno' in x):
        x=x.replace(x,'Electronic')
        return x
    if ('Electro-Industrial' in x):
        x=x.replace(x,'Electronic')
        return x
    if ('Glitch' in x):
        x=x.replace(x,'Electronic')
        return x
    if ('Deep House' in x):
        x=x.replace(x,'Electronic')
        return x
    if ("Microhouse" in x):
        x=x.replace(x,'Electronic')
        return x
    if ("Atmospheric Drumand Bass" in x):
        x=x.replace(x,'Electronic')
        return x
    if ("Chillwave" in x):
        x=x.replace(x,'Electronic')
        return x
    if ("Berlin School" in x):
        x=x.replace(x,'Electronic')
        return x
    if ("Vaporwave" in x):
        x=x.replace(x,'Electronic')
        return x
    if ("Deconstructed Club" in x):
        x=x.replace(x,'Electronic')
        return x
    if ("Future Garage" in x):
        x=x.replace(x,'Electronic')
        return x
    if ("Indietronica" in x):
        x=x.replace(x,'Electronic')
        return x
    if ("Dungeon Synth" in x):
        x=x.replace(x,'Electronic')
        return x
    if ("French House" in x):
        x=x.replace(x,'Electronic')
        return x
    if ("UKBass" in x):
        x=x.replace(x,'Electronic')
        return x
    if ("Wonky" in x):
        x=x.replace(x,'Electronic')
        return x
    if ("Minimal Synth" in x):
        x=x.replace(x,'Electronic')
        return x
    if ("Progressive House" in x):
        x=x.replace(x,'Electronic')
        return x
    if ("Electro-Disco" in x):
        x=x.replace(x,'Electronic')
        return x
    if ("Outsider House" in x):
        x=x.replace(x,'Electronic')
        return x
    if ("Drilland Bass" in x):
        x=x.replace(x,'Electronic')
        return x
    if ("Acid House" in x):
        x=x.replace(x,'Electronic')
        return x
    if ("Electronic" in x):
        x=x.replace(x,'Electronic')
        return x
    if ("Electro" in x):
        x=x.replace(x,'Electronic')
        return x
    if ("Big Room" in x):
        x=x.replace(x,'Electronic')
        return x
    if ("Edm" in x):
        x=x.replace(x,'Electronic')
        return x
    if ("Eurodance" in x):
        x=x.replace(x,'Electronic')
        return x
    if ("Gabba" in x):
        x=x.replace(x,'Electronic')
        return x
    if ("Electro House" in x):
        x=x.replace(x,'Electronic')
        return x
    if ("Basshall" in x):
        x=x.replace(x,'Electronic')
        return x
    if ("J-Core" in x):
        x=x.replace(x,'Electronic')
        return x
    if ("Trance" in x):
        x=x.replace(x,'Electronic')
        return x
    if ("Adult Standards" in x):
        x=x.replace(x,'Adult Standards')
        return x
    else:
        return x

df5 ['genre'].value_counts().head(40)
df5['genre']=df5['genre'].str.title()

df5['genre'] = df5['genre'].apply(normalize_genres)

df5['genre'].value_counts().head(60)

Rock                          1007
Pop                            386
Adult Standards                123
Metal                           93
Dutch Cabaret                   51
Soul                            47
Electronic                      43
British Invasion                36
Funk                            36
Hip-Hop                         30
Folk                            21
Neo Mellow                      17
Alternative Dance               15
Reggae                          12
Country                         12
Dutch Americana                 12
Carnaval Limburg                10
Chanson                          9
Blues                            8
Celtic                           5
Jazz                             3
Christelijk                      3
Scottish Singer-Songwriter       2
Latin                            2
Laboratorio                      1
Australian Americana             1
Streektaal                       1
Classic Soundtrack               1
Alaska Indie                     1
Australian Dance                 1
Stomp And Holler                 1
Irish Singer-Songwriter          1
British Singer-Songwriter        1
Happy Hardcore                   1
Bebop                            1
Name: genre, dtype: int64

In [23]:
df5[df5['genre']=='Adult Standards'].head(40)

            artist_name            genre  year  popularity
0           norah jones  Adult Standards  2004          71
10        elvis presley  Adult Standards  2002          49
33          norah jones  Adult Standards  2002          74
48          barry white  Adult Standards  2009          67
124     the temptations  Adult Standards  2001          44
138       michael bublÃ©  Adult Standards  2005          64
144       elvis presley  Adult Standards  2002          64
167       michael bublÃ©  Adult Standards  2007          73
211             tavares  Adult Standards  2004          49
218            bee gees  Adult Standards  2001          47
230       michael bublÃ©  Adult Standards  2005          64
267           sam cooke  Adult Standards  2000          71
275       lionel richie  Adult Standards  2003          64
315       stevie wonder  Adult Standards  2002          77
336     sammy davis jr.  Adult Standards  2002          56
387       elvis presley  Adult Standards  2002          65
426         roy orbison  Adult Standards  2010          44
476         ray charles  Adult Standards  2011          49
627       frank sinatra  Adult Standards  2015          68
664       elvis presley  Adult Standards  2016          44
716        neil diamond  Adult Standards  2017          40
827        james taylor  Adult Standards  1970          73
829             chicago  Adult Standards  1970          64
834          carpenters  Adult Standards  1970          60
843          don mclean  Adult Standards  1971          69
847        neil diamond  Adult Standards  1971          60
853          don mclean  Adult Standards  1971          74
858  gilbert o'sullivan  Adult Standards  1971          35
860         carole king  Adult Standards  1971          68
866        james taylor  Adult Standards  1971          68
870         rod stewart  Adult Standards  1971          72
889           jim croce  Adult Standards  1972          58
895         carly simon  Adult Standards  1972          75
899          carpenters  Adult Standards  1972          65
907        neil diamond  Adult Standards  1972          54
918       elvis presley  Adult Standards  1973          61
921         john denver  Adult Standards  1973          64
928       elvis presley  Adult Standards  1973          68
934           jim croce  Adult Standards  1973          53
945         john denver  Adult Standards  1974          69

In [15]:
filter_norah = df5[(df5['genre']=='Adult Standards') & (df5['artist_name']=='norah jones')]

In [16]:
filter_norah['genre'].apply(lambda x: x.replace('Adult Standards','Jazz'))

0     Jazz
33    Jazz
Name: genre, dtype: object

In [ ]:
filter_norah['genre'].apply(lambda x: x.replace('Adult Standards','Jazz'))

In [ ]:
df5[df5['genre']=='Adult Standards']

In [17]:
df5[(df5['genre']=='Adult Standards') & (df5['artist_name']=='norah jones')]['genre']

0     Adult Standards
33    Adult Standards
Name: genre, dtype: object

In [21]:
df5[df5['genre']=='Adult Standards']

          artist_name            genre  year  popularity
0         norah jones  Adult Standards  2004          71
10      elvis presley  Adult Standards  2002          49
33        norah jones  Adult Standards  2002          74
48        barry white  Adult Standards  2009          67
124   the temptations  Adult Standards  2001          44
...               ...              ...   ...         ...
1987      nina simone  Adult Standards  1958          68
1988  louis armstrong  Adult Standards  1958          66
1989    elvis presley  Adult Standards  1958          63
1990    elvis presley  Adult Standards  1958          69
1993      fats domino  Adult Standards  1959          56

[123 rows x 4 columns]

In [ ]:
df8 = df5.copy()
df8['genre'].value_counts().head(60) # Adult standarts give some relevance but it's not possible to
    #classify as a musical genre, However this represent 6 % of the data frame
(df8['genre'].value_counts())*100/(df5.shape[0])

In [ ]:
df5['genre'] = df5['genre'].str.lower()

In [24]:
df5

                   artist_name            genre  year  popularity
0                  norah jones  Adult Standards  2004          71
1                  deep purple             Rock  2000          39
2                     gorillaz          Hip-Hop  2001          69
3                 foo fighters            Metal  2007          76
4            bruce springsteen             Rock  2002          59
...                        ...              ...   ...         ...
1989             elvis presley  Adult Standards  1958          63
1990             elvis presley  Adult Standards  1958          69
1991               chuck berry             Rock  1959          74
1992  the dave brubeck quartet            Bebop  1959          65
1993               fats domino  Adult Standards  1959          56

[1994 rows x 4 columns]

In [25]:
df5.to_csv('../../../Data/cleaned_data/5. Spotify-2000.csv', index = False)