In [1]:

import pandas as pd

most_popular_albuns_and_nominated_artists = pd.read_csv('../../Data/cleaned_data/merged_data/most_popular_albuns_and_nominated_artists.csv')

#spotify_top_hits_2000_2019 = pd.read_csv('../../Data/cleaned_data/3. Top Hits Spotify from 2000-2019[CLEANED].csv')

best_selling_artists_of_all_time = pd.read_csv('../../Data/cleaned_data/4. best_selling_artists_of_all_time[CLEANED].csv')

#spotify_most_played_songs_of_all_time = pd.read_csv('../../Data/cleaned_data/5. Spotify-2000.csv')

In [2]:
most_popular_albuns_and_nominated_artists

,Unnamed: 0,popular_ranking,artist_name,release_date,genre,total_awards_nominations,uk number 1's
0,0,1.0,radiohead,1997.0,rock,18.0,0.0
1,1,2.0,radiohead,2000.0,rock,18.0,0.0
2,2,6.0,radiohead,2007.0,rock,18.0,0.0
3,3,9.0,radiohead,1995.0,rock,18.0,0.0
4,4,21.0,radiohead,2001.0,rock,18.0,0.0
...,...,...,...,...,...,...,...
4863,4863,0.0,the drifters,1900.0,soul,1.0,0.0
4864,4864,0.0,james taylor,1900.0,folk,18.0,0.0
4865,4865,0.0,booker t & the mg's,1900.0,soul,4.0,0.0
4866,4866,0.0,diana ross and the supremes,1900.0,soul,2.0,1.0
4867,4867,0.0,carl perkins,1900.0,rock,2.0,0.0

In [3]:
best_selling_artists_of_all_time

         artist_name         country  year      genre  sales
0        the beatles  united kingdom  1962       Rock    600
1      elvis presley   united states  1956       Rock    500
2    michael jackson   united states  1971        Pop    400
3         elton john  united kingdom  1970        Pop    300
4              queen  united kingdom  1973       Rock    300
..               ...             ...   ...        ...    ...
116       the police  united kingdom  1978        Pop     75
117   gloria estefan   united states  1984  Latin pop     75
118    barry manilow   united states  1973        Pop     75
119             kiss   united states  1974       Rock     75
120  aretha franklin   united states  1961       Soul     75

[121 rows x 5 columns]

In [4]:
a = most_popular_albuns_and_nominated_artists
b = best_selling_artists_of_all_time

most_popular_albuns_and_nominated_artists_with_sales = pd.merge(left = a, right = b, left_on = 'artist_name', 
                                                   right_on = 'artist_name', how = 'outer' )

most_popular_albuns_and_nominated_artists_with_sales.tail(50)

,Unnamed: 0,popular_ranking,artist_name,release_date,genre_x,total_awards_nominations,uk number 1's,country,year,genre_y,sales
4863,4863.0,0.0,the drifters,1900.0,soul,1.0,0.0,NaN,NaN,NaN,NaN
4864,4864.0,0.0,james taylor,1900.0,folk,18.0,0.0,united states,1970.0,Rock,100.0
4865,4865.0,0.0,booker t & the mg's,1900.0,soul,4.0,0.0,NaN,NaN,NaN,NaN
4866,4866.0,0.0,diana ross and the supremes,1900.0,soul,2.0,1.0,NaN,NaN,NaN,NaN
4867,4867.0,0.0,carl perkins,1900.0,rock,2.0,0.0,NaN,NaN,NaN,NaN
4868,NaN,NaN,mariah carey,NaN,NaN,NaN,NaN,united states,1990.0,Soul,220.0
4869,NaN,NaN,whitney houston,NaN,NaN,NaN,NaN,united states,1984.0,Soul,200.0
4870,NaN,NaN,celine dion,NaN,NaN,NaN,NaN,canada,1981.0,Rock,200.0
4871,NaN,NaN,garth brooks,NaN,NaN,NaN,NaN,united states,1989.0,Country,170.0
4872,NaN,NaN,barbra streisand,NaN,NaN,NaN,NaN,united states,1963.0,Pop,150.0
4873,NaN,NaN,chris brown,NaN,NaN,NaN,NaN,united states,2005.0,Pop,140.0
4874,NaN,NaN,bee gees,NaN,NaN,NaN,NaN,united kingdom,1963.0,Pop,120.0
4875,NaN,NaN,george strait,NaN,NaN,NaN,NaN,united states,1984.0,Country,100.0
4876,NaN,NaN,pink,NaN,NaN,NaN,NaN,united states,2000.0,Pop,100.0
4877,NaN,NaN,b'z,NaN,NaN,NaN,NaN,japan,1988.0,Rock,100.0
4878,NaN,NaN,shania twain,NaN,NaN,NaN,NaN,canada,1993.0,Country,100.0
4879,NaN,NaN,backstreet boys,NaN,NaN,NaN,NaN,united states,1995.0,Pop,100.0
4880,NaN,NaN,neil diamond,NaN,NaN,NaN,NaN,united states,1966.0,Pop,100.0
4881,NaN,NaN,journey,NaN,NaN,NaN,NaN,united states,1975.0,Rock,100.0
4882,NaN,NaN,kenny rogers,NaN,NaN,NaN,NaN,united states,1975.0,Country,100.0
4883,NaN,NaN,julio iglesias,NaN,NaN,NaN,NaN,spain,1968.0,Latin pop,100.0
4884,NaN,NaN,foreigner,NaN,NaN,NaN,NaN,united states,1977.0,Rock,100.0
4885,NaN,NaN,chicago,NaN,NaN,NaN,NaN,united states,1969.0,Rock,100.0
4886,NaN,NaN,the carpenters,NaN,NaN,NaN,NaN,united states,1969.0,Pop,100.0
4887,NaN,NaN,"earth, wind & fire",NaN,NaN,NaN,NaN,united states,1971.0,Soul,100.0
4888,NaN,NaN,cher,NaN,NaN,NaN,NaN,united states,1965.0,Pop,100.0
4889,NaN,NaN,olivia newton-john,NaN,NaN,NaN,NaN,australia,1966.0,Pop,100.0
4890,NaN,NaN,linda ronstadt,NaN,NaN,NaN,NaN,united states,1968.0,Rock,100.0
4891,NaN,NaN,donna summer,NaN,NaN,NaN,NaN,united states,1974.0,Pop,100.0
4892,NaN,NaN,alicia keys,NaN,NaN,NaN,NaN,united states,2001.0,Soul,90.0
4893,NaN,NaN,christina aguilera,NaN,NaN,NaN,NaN,united states,1998.0,Soul,901.0
4894,NaN,NaN,lionel richie,NaN,NaN,NaN,NaN,united states,1981.0,Pop,90.0
4895,NaN,NaN,flo rida,NaN,NaN,NaN,NaN,united states,2007.0,Hip-Hop,80.0
4896,NaN,NaN,usher,NaN,NaN,NaN,NaN,united states,1994.0,Soul,80.0
4897,NaN,NaN,shakira,NaN,NaN,NaN,NaN,colombia,1995.0,Latin pop,80.0
4898,NaN,NaN,tim mcgraw,NaN,NaN,NaN,NaN,united states,1994.0,Country,80.0
4899,NaN,NaN,ayumi hamasaki,NaN,NaN,NaN,NaN,japan,1998.0,Electronic,80.0
4900,NaN,NaN,johnny hallyday,NaN,NaN,NaN,NaN,france,1960.0,Rock,80.0
4901,NaN,NaN,luke bryan,NaN,NaN,NaN,NaN,united states,2007.0,Country,75.0
4902,NaN,NaN,tupac shakur,NaN,NaN,NaN,NaN,united states,1991.0,Hip-Hop,75.0
4903,NaN,NaN,alabama,NaN,NaN,NaN,NaN,united states,1980.0,Country,75.0
4904,NaN,NaN,r. kelly,NaN,NaN,NaN,NaN,united states,1991.0,Soul,75.0
4905,NaN,NaN,robbie williams,NaN,NaN,NaN,NaN,united kingdom,1996.0,Pop,75.0
4906,NaN,NaN,bob seger,NaN,NaN,NaN,NaN,united states,1967.0,Rock,75.0
4907,NaN,NaN,kenny g,NaN,NaN,NaN,NaN,united states,1984.0,Jazz,75.0
4908,NaN,NaN,enya,NaN,NaN,NaN,NaN,ireland,1987.0,New-age / Celtic,75.0
4909,NaN,NaN,bryan adams,NaN,NaN,NaN,NaN,canada,1979.0,Rock,75.0
4910,NaN,NaN,bob marley,NaN,NaN,NaN,NaN,jamaica,1975.0,Reggae,75.0
4911,NaN,NaN,gloria estefan,NaN,NaN,NaN,NaN,united states,1984.0,Latin pop,75.0
4912,NaN,NaN,barry manilow,NaN,NaN,NaN,NaN,united states,1973.0,Pop,75.0

In [5]:
#drop columns that we'll don't need to achieve the project main goals
   
most_popular_albuns_and_nominated_artists_with_sales = most_popular_albuns_and_nominated_artists_with_sales.drop(['country','Unnamed: 0'], axis = 1)

In [6]:
most_popular_albuns_and_nominated_artists_with_sales

,popular_ranking,artist_name,release_date,genre_x,total_awards_nominations,uk number 1's,year,genre_y,sales
0,1.0,radiohead,1997.0,rock,18.0,0.0,NaN,NaN,NaN
1,2.0,radiohead,2000.0,rock,18.0,0.0,NaN,NaN,NaN
2,6.0,radiohead,2007.0,rock,18.0,0.0,NaN,NaN,NaN
3,9.0,radiohead,1995.0,rock,18.0,0.0,NaN,NaN,NaN
4,21.0,radiohead,2001.0,rock,18.0,0.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
4908,NaN,enya,NaN,NaN,NaN,NaN,1987.0,New-age / Celtic,75.0
4909,NaN,bryan adams,NaN,NaN,NaN,NaN,1979.0,Rock,75.0
4910,NaN,bob marley,NaN,NaN,NaN,NaN,1975.0,Reggae,75.0
4911,NaN,gloria estefan,NaN,NaN,NaN,NaN,1984.0,Latin pop,75.0
4912,NaN,barry manilow,NaN,NaN,NaN,NaN,1973.0,Pop,75.0

In [7]:
most_popular_albuns_and_nominated_artists_with_sales.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4913 entries, 0 to 4912
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   popular_ranking           4868 non-null   float64
 1   artist_name               4913 non-null   object
 2   release_date              4868 non-null   float64
 3   genre_x                   4867 non-null   object
 4   total_awards_nominations  4868 non-null   float64
 5   uk number 1's             4868 non-null   float64
 6   year                      528 non-null    float64
 7   genre_y                   528 non-null    object
 8   sales                     528 non-null    float64
dtypes: float64(6), object(3)
memory usage: 383.8+ KB

In [8]:
d_test = most_popular_albuns_and_nominated_artists_with_sales[most_popular_albuns_and_nominated_artists_with_sales['popular_ranking'].isna() == True]
d_test.shape
# it's good to check if this artists are not included in the df most_popular_albuns so we can see if the merge went good

list1 = list(d_test['artist_name'])
most_popular_albuns_and_nominated_artists['popular_ranking'].isin(list1).value_counts() #--> all false: ok!
    # merge went's good since none of that artist is in the df 'most_popular_albuns'
    
d_test2 = most_popular_albuns_and_nominated_artists_with_sales[most_popular_albuns_and_nominated_artists_with_sales['release_date'].isna() == True]#--> all false: ok!
d_test2.shape
     # merge went's good by checking the missing values in the column release_date
    
list1 = list(d_test['artist_name'])
most_popular_albuns_and_nominated_artists['total_awards_nominations'].isin(list1).value_counts() #--> all false: ok!
    # merge went's good since none of that artist is in the df 'most_popular_albuns'

(45, 9)

In [19]:
# Now it is important to fill the missing values of column genre_x with the information contained in the column genre_y

#d_test2['genre_x'] = d_test2['genre_y'].str.lower()

most_popular_albuns_and_nominated_artists_with_sales[most_popular_albuns_and_nominated_artists_with_sales['popular_ranking'].\
                                                     isna() == True]
#d_test2['release_date'] = d_test2['year']

most_popular_albuns_and_nominated_artists_with_sales[most_popular_albuns_and_nominated_artists_with_sales['popular_ranking'].isna() == True]['release_date'] = most_popular_albuns_and_nominated_artists_with_sales[most_popular_albuns_and_nominated_artists_with_sales['popular_ranking'].isna() == True]['year']

C:\Users\Admin\AppData\Local\Temp\ipykernel_20664\3526986463.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  most_popular_albuns_and_nominated_artists_with_sales[most_popular_albuns_and_nominated_artists_with_sales['popular_ranking'].isna() == True]['release_date'] = most_popular_albuns_and_nominated_artists_with_sales[most_popular_albuns_and_nominated_artists_with_sales['popular_ranking'].isna() == True]['year']

In [20]:
most_popular_albuns_and_nominated_artists_with_sales[most_popular_albuns_and_nominated_artists_with_sales['popular_ranking'].\
                                                     isna() == True]

,popular_ranking,artist_name,release_date,genre_x,total_awards_nominations,uk number 1's,year,genre_y,sales
4868,NaN,mariah carey,NaN,NaN,NaN,NaN,1990.0,Soul,220.0
4869,NaN,whitney houston,NaN,NaN,NaN,NaN,1984.0,Soul,200.0
4870,NaN,celine dion,NaN,NaN,NaN,NaN,1981.0,Rock,200.0
4871,NaN,garth brooks,NaN,NaN,NaN,NaN,1989.0,Country,170.0
4872,NaN,barbra streisand,NaN,NaN,NaN,NaN,1963.0,Pop,150.0
4873,NaN,chris brown,NaN,NaN,NaN,NaN,2005.0,Pop,140.0
4874,NaN,bee gees,NaN,NaN,NaN,NaN,1963.0,Pop,120.0
4875,NaN,george strait,NaN,NaN,NaN,NaN,1984.0,Country,100.0
4876,NaN,pink,NaN,NaN,NaN,NaN,2000.0,Pop,100.0
4877,NaN,b'z,NaN,NaN,NaN,NaN,1988.0,Rock,100.0
4878,NaN,shania twain,NaN,NaN,NaN,NaN,1993.0,Country,100.0
4879,NaN,backstreet boys,NaN,NaN,NaN,NaN,1995.0,Pop,100.0
4880,NaN,neil diamond,NaN,NaN,NaN,NaN,1966.0,Pop,100.0
4881,NaN,journey,NaN,NaN,NaN,NaN,1975.0,Rock,100.0
4882,NaN,kenny rogers,NaN,NaN,NaN,NaN,1975.0,Country,100.0
4883,NaN,julio iglesias,NaN,NaN,NaN,NaN,1968.0,Latin pop,100.0
4884,NaN,foreigner,NaN,NaN,NaN,NaN,1977.0,Rock,100.0
4885,NaN,chicago,NaN,NaN,NaN,NaN,1969.0,Rock,100.0
4886,NaN,the carpenters,NaN,NaN,NaN,NaN,1969.0,Pop,100.0
4887,NaN,"earth, wind & fire",NaN,NaN,NaN,NaN,1971.0,Soul,100.0
4888,NaN,cher,NaN,NaN,NaN,NaN,1965.0,Pop,100.0
4889,NaN,olivia newton-john,NaN,NaN,NaN,NaN,1966.0,Pop,100.0
4890,NaN,linda ronstadt,NaN,NaN,NaN,NaN,1968.0,Rock,100.0
4891,NaN,donna summer,NaN,NaN,NaN,NaN,1974.0,Pop,100.0
4892,NaN,alicia keys,NaN,NaN,NaN,NaN,2001.0,Soul,90.0
4893,NaN,christina aguilera,NaN,NaN,NaN,NaN,1998.0,Soul,901.0
4894,NaN,lionel richie,NaN,NaN,NaN,NaN,1981.0,Pop,90.0
4895,NaN,flo rida,NaN,NaN,NaN,NaN,2007.0,Hip-Hop,80.0
4896,NaN,usher,NaN,NaN,NaN,NaN,1994.0,Soul,80.0
4897,NaN,shakira,NaN,NaN,NaN,NaN,1995.0,Latin pop,80.0
4898,NaN,tim mcgraw,NaN,NaN,NaN,NaN,1994.0,Country,80.0
4899,NaN,ayumi hamasaki,NaN,NaN,NaN,NaN,1998.0,Electronic,80.0
4900,NaN,johnny hallyday,NaN,NaN,NaN,NaN,1960.0,Rock,80.0
4901,NaN,luke bryan,NaN,NaN,NaN,NaN,2007.0,Country,75.0
4902,NaN,tupac shakur,NaN,NaN,NaN,NaN,1991.0,Hip-Hop,75.0
4903,NaN,alabama,NaN,NaN,NaN,NaN,1980.0,Country,75.0
4904,NaN,r. kelly,NaN,NaN,NaN,NaN,1991.0,Soul,75.0
4905,NaN,robbie williams,NaN,NaN,NaN,NaN,1996.0,Pop,75.0
4906,NaN,bob seger,NaN,NaN,NaN,NaN,1967.0,Rock,75.0
4907,NaN,kenny g,NaN,NaN,NaN,NaN,1984.0,Jazz,75.0
4908,NaN,enya,NaN,NaN,NaN,NaN,1987.0,New-age / Celtic,75.0
4909,NaN,bryan adams,NaN,NaN,NaN,NaN,1979.0,Rock,75.0
4910,NaN,bob marley,NaN,NaN,NaN,NaN,1975.0,Reggae,75.0
4911,NaN,gloria estefan,NaN,NaN,NaN,NaN,1984.0,Latin pop,75.0
4912,NaN,barry manilow,NaN,NaN,NaN,NaN,1973.0,Pop,75.0

In [21]:
d_test2.shape

(45, 9)

In [ ]:
# Now the same but for the column release_year and year
d_test2['release_date'] = d_test2['year']

In [ ]:
d_test2

In [22]:
a=4912-4868

In [26]:
most_popular_albuns_and_nominated_artists_with_sales.loc[4868:4912,['genre_x']] = most_popular_albuns_and_nominated_artists_with_sales['genre_y']

In [28]:
most_popular_albuns_and_nominated_artists_with_sales.loc[4868:4912,['release_date']] = most_popular_albuns_and_nominated_artists_with_sales['year']

In [29]:
most_popular_albuns_and_nominated_artists_with_sales[most_popular_albuns_and_nominated_artists_with_sales['popular_ranking'].\
                                                     isna() == True]

,popular_ranking,artist_name,release_date,genre_x,total_awards_nominations,uk number 1's,year,genre_y,sales
4868,NaN,mariah carey,1990.0,Soul,NaN,NaN,1990.0,Soul,220.0
4869,NaN,whitney houston,1984.0,Soul,NaN,NaN,1984.0,Soul,200.0
4870,NaN,celine dion,1981.0,Rock,NaN,NaN,1981.0,Rock,200.0
4871,NaN,garth brooks,1989.0,Country,NaN,NaN,1989.0,Country,170.0
4872,NaN,barbra streisand,1963.0,Pop,NaN,NaN,1963.0,Pop,150.0
4873,NaN,chris brown,2005.0,Pop,NaN,NaN,2005.0,Pop,140.0
4874,NaN,bee gees,1963.0,Pop,NaN,NaN,1963.0,Pop,120.0
4875,NaN,george strait,1984.0,Country,NaN,NaN,1984.0,Country,100.0
4876,NaN,pink,2000.0,Pop,NaN,NaN,2000.0,Pop,100.0
4877,NaN,b'z,1988.0,Rock,NaN,NaN,1988.0,Rock,100.0
4878,NaN,shania twain,1993.0,Country,NaN,NaN,1993.0,Country,100.0
4879,NaN,backstreet boys,1995.0,Pop,NaN,NaN,1995.0,Pop,100.0
4880,NaN,neil diamond,1966.0,Pop,NaN,NaN,1966.0,Pop,100.0
4881,NaN,journey,1975.0,Rock,NaN,NaN,1975.0,Rock,100.0
4882,NaN,kenny rogers,1975.0,Country,NaN,NaN,1975.0,Country,100.0
4883,NaN,julio iglesias,1968.0,Latin pop,NaN,NaN,1968.0,Latin pop,100.0
4884,NaN,foreigner,1977.0,Rock,NaN,NaN,1977.0,Rock,100.0
4885,NaN,chicago,1969.0,Rock,NaN,NaN,1969.0,Rock,100.0
4886,NaN,the carpenters,1969.0,Pop,NaN,NaN,1969.0,Pop,100.0
4887,NaN,"earth, wind & fire",1971.0,Soul,NaN,NaN,1971.0,Soul,100.0
4888,NaN,cher,1965.0,Pop,NaN,NaN,1965.0,Pop,100.0
4889,NaN,olivia newton-john,1966.0,Pop,NaN,NaN,1966.0,Pop,100.0
4890,NaN,linda ronstadt,1968.0,Rock,NaN,NaN,1968.0,Rock,100.0
4891,NaN,donna summer,1974.0,Pop,NaN,NaN,1974.0,Pop,100.0
4892,NaN,alicia keys,2001.0,Soul,NaN,NaN,2001.0,Soul,90.0
4893,NaN,christina aguilera,1998.0,Soul,NaN,NaN,1998.0,Soul,901.0
4894,NaN,lionel richie,1981.0,Pop,NaN,NaN,1981.0,Pop,90.0
4895,NaN,flo rida,2007.0,Hip-Hop,NaN,NaN,2007.0,Hip-Hop,80.0
4896,NaN,usher,1994.0,Soul,NaN,NaN,1994.0,Soul,80.0
4897,NaN,shakira,1995.0,Latin pop,NaN,NaN,1995.0,Latin pop,80.0
4898,NaN,tim mcgraw,1994.0,Country,NaN,NaN,1994.0,Country,80.0
4899,NaN,ayumi hamasaki,1998.0,Electronic,NaN,NaN,1998.0,Electronic,80.0
4900,NaN,johnny hallyday,1960.0,Rock,NaN,NaN,1960.0,Rock,80.0
4901,NaN,luke bryan,2007.0,Country,NaN,NaN,2007.0,Country,75.0
4902,NaN,tupac shakur,1991.0,Hip-Hop,NaN,NaN,1991.0,Hip-Hop,75.0
4903,NaN,alabama,1980.0,Country,NaN,NaN,1980.0,Country,75.0
4904,NaN,r. kelly,1991.0,Soul,NaN,NaN,1991.0,Soul,75.0
4905,NaN,robbie williams,1996.0,Pop,NaN,NaN,1996.0,Pop,75.0
4906,NaN,bob seger,1967.0,Rock,NaN,NaN,1967.0,Rock,75.0
4907,NaN,kenny g,1984.0,Jazz,NaN,NaN,1984.0,Jazz,75.0
4908,NaN,enya,1987.0,New-age / Celtic,NaN,NaN,1987.0,New-age / Celtic,75.0
4909,NaN,bryan adams,1979.0,Rock,NaN,NaN,1979.0,Rock,75.0
4910,NaN,bob marley,1975.0,Reggae,NaN,NaN,1975.0,Reggae,75.0
4911,NaN,gloria estefan,1984.0,Latin pop,NaN,NaN,1984.0,Latin pop,75.0
4912,NaN,barry manilow,1973.0,Pop,NaN,NaN,1973.0,Pop,75.0

In [36]:
most_popular_albuns_and_nominated_artists_with_sales['total_awards_nominations'] = most_popular_albuns_and_nominated_artists_with_sales['total_awards_nominations'].fillna(0)
most_popular_albuns_and_nominated_artists_with_sales["uk number 1's"] = most_popular_albuns_and_nominated_artists_with_sales["uk number 1's"].fillna(0)

In [37]:
most_popular_albuns_and_nominated_artists_with_sales.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4913 entries, 0 to 4912
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   popular_ranking           4868 non-null   float64
 1   artist_name               4913 non-null   object
 2   release_date              4913 non-null   float64
 3   genre_x                   4912 non-null   object
 4   total_awards_nominations  4913 non-null   float64
 5   uk number 1's             4913 non-null   float64
 6   year                      528 non-null    float64
 7   genre_y                   528 non-null    object
 8   sales                     528 non-null    float64
dtypes: float64(6), object(3)
memory usage: 512.9+ KB